Proj. 7, Pt. 1: removed compiler errors and added some includes.
hilberturi/PFMCPP_Project7 pull request #1
Opened 2023-02-08 15:11 UTC by hilberturi

Now there are linker errors.

2023-02-09 18:48 UTC, matkatmusic requested changes

2023-02-09 18:48 UTC, matkatmusic commented on Character.cpp
> +        *initialArmorLevel = armor;
You are doing the same thing three times with different pairs of variables.
Recognize the pattern.
Don't repeat yourself.
Write a free function and call it three times.  The argument list should not include `std::unique_ptr`.
- [ ] revise

2023-02-09 18:48 UTC, matkatmusic commented on Character.cpp
>  }
Do not change the base class
- [ ] revert

2023-02-09 18:48 UTC, matkatmusic commented on Character.h
> +    Character(int hp, int armor_, int attackDamage_, int numDefensiveItems = chooseItemCount(), int numHelpfulItems = chooseItemCount());
Do not change the base class
- [ ] revert

2023-02-09 18:48 UTC, matkatmusic commented on DragonSlayer.cpp
> +            }
Do this before all of the attacking.
You are currently doing this **during** the attacking
- [ ] revise

2023-02-09 18:48 UTC, matkatmusic commented on Utility.cpp
> +}
Casting has not been covered (it's covered in the next project).
Statics have not been covered
- [ ] remove this.

2023-02-09 18:48 UTC, matkatmusic commented on Utility.h
> +
The dragon slayer gets one attack item, not a vector of them. This function is unnecessary.
- [ ] remove

2023-02-11 05:37 UTC, matkatmusic requested changes

2023-02-11 05:37 UTC, matkatmusic commented on Character.cpp
> +    *initialLevelPtr = stat;
You're dereferencing 3 times here.
You don't need to.
The first argument to this function is a reference.
Why can't the 2nd argument to this function also be a reference?
- [ ] revise

2023-02-11 05:37 UTC, matkatmusic commented on Character.cpp
> +        restoreAndBoostStats (armor, initialArmorLevel.get());
There is no need to `get()` when you can dereference.
See:
https://en.cppreference.com/w/cpp/memory/unique_ptr/operator*
- [ ] revise

2023-02-11 06:29 UTC, hilberturi commented on Character.cpp
> +    *initialLevelPtr = stat;
Good point, I have now improved this.

2023-02-11 06:31 UTC, hilberturi commented on Character.cpp
> +        restoreAndBoostStats (armor, initialArmorLevel.get());
The link seems to be broken but I found the page on cppreference.com anyway.
Using get() is now avoded by dereferencing and passing the reference.

2023-02-11 06:41 UTC, matkatmusic approved these changes

2023-02-11 06:41 UTC, merged